name: Test JLL
on:
  - push

defaults:
  run:
    shell: bash

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      binarybuilder: ${{ steps.changes.outputs.binarybuilder }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            binarybuilder:
              - 'binarybuilder/**'
              - '.github/workflows/binary-builder.yml'

  buildjll:
    name: Build JLL
    needs: changes
    if: needs.changes.outputs.binarybuilder == 'true'
    runs-on: ubuntu-latest
    steps:
      # To let BinaryBuilder increase the patch number automatically.
      # - run: julia -e 'using Pkg; pkg"registry add General https://github.com/epolack/HollvedRegistry.jl"'
      - uses: julia-actions/add-julia-registry@v1
        with:
          # Does not allow PAT yet (https://github.com/julia-actions/add-julia-registry/issues/20)
          key: ${{ secrets.SSH_KEY }}
          registry: epolack/HollvedRegistry.jl


      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'
          arch: x64

      - name: Build JLLs
        run: |
          git config --global user.name "Github_Action"
          git config --global user.email "github_action@example.test"
          julia --project=./binarybuilder -e "using Pkg; Pkg.instantiate()"

      - name: Deploying locally
        env:
          BINARYBUILDER_RUNNER: privileged
          BINARYBUILDER_USE_SQUASHFS: true
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: julia --project=./binarybuilder ./binarybuilder/build_tarballs.jl --deploy=local
        if: github.ref != 'refs/heads/main'

      - name: Deploying
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
          BINARYBUILDER_RUNNER: privileged
          BINARYBUILDER_USE_SQUASHFS: true
          BINARYBUILDER_AUTOMATIC_APPLE: true
        if: github.ref == 'refs/heads/main'
        run: |
          julia --project=./binarybuilder ./binarybuilder/build_tarballs.jl --deploy=epolack/ABINIT_jll.jl

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

  update_registry:
    name: "Updating local Registry"
    needs: [buildjll]
    if: always() && !cancelled() && contains(needs.*.result, 'success') && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master version of JLL
        uses: actions/checkout@v4
        with:
          repository: epolack/ABINIT_jll.jl

      - uses: julia-actions/add-julia-registry@v1
        with:
          # Does not allow PAT yet (https://github.com/julia-actions/add-julia-registry/issues/20)
          key: ${{ secrets.SSH_KEY }}
          registry: epolack/HollvedRegistry.jl

      - name: Deploying to registry
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
        run: |
          rm -rf ~/.julia/registries/HollvedRegistry  # but why?
          julia -e 'import Pkg; Pkg.add("LocalRegistry"); using LocalRegistry; Pkg.activate("."); Pkg.instantiate(); using ABINIT_jll; register(ABINIT_jll; gitconfig=Dict("user.name" => "Github Actions", "user.email" => "github_action@example.test"))'


  test_jll:
    name: "Testing JLL"
    needs: [buildjll]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia stable
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
          arch: x64

      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-jll-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-jll-${{ env.cache-name }}-
            ${{ runner.os }}-jll-
            ${{ runner.os }}-

      - uses: julia-actions/julia-buildpkg@v1
        with:
          localregistry: |
            https://github.com/epolack/HollvedRegistry.jl
      - uses: julia-actions/julia-runtest@v1
