name: testjll
on:
  - push

defaults:
  run:
    shell: bash

jobs:
  buildjll:
    name: Build JLL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
          arch: x64
      - name: Cache artifacts
        uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-jll-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-jll-${{ env.cache-name }}-
            ${{ runner.os }}-jll-
            ${{ runner.os }}-
      - name: Build JLLs
        env:
          # Needs old token because of check on its size.
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
          BINARYBUILDER_RUNNER: privileged
          BINARYBUILDER_USE_SQUASHFS: true
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: |
          git config --global user.name "Github_Action"
          git config --global user.email "github_action@example.test"
          julia --project=./binarybuilder -e "using Pkg; Pkg.instantiate()"
          julia --project=./binarybuilder ./binarybuilder/build_tarballs.jl --deploy=epolack/ABINIT_jll.jl
